### ISSUE TITLE
Do you guys use a DB? Do you have any DB tips for React projects?

### ISSUE THREAD

**Issue by naazy** [dwyl/setup#5]

**Comment by jrans** [comment]
There is no backend in this set up. Loading and saving data in and out of the project is your responsibility. This [article](http://andrewhfarmer.com/react-ajax-best-practices/?utm_campaign=Fullstack%2BReact&utm_medium=web&utm_source=Fullstack_React_7) may prove useful

**Comment by naazy** [comment]
thanks
